# Generated by Django 5.2.4 on 2025-07-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedores',
            field=models.ManyToManyField(to='index.fornecedor'),
        ),
    ]
